### ISSUE TITLE
Problem running project

### ISSUE THREAD

**Issue by johnfcporto** [Christian-Schiffer/servicelayer.chat#1]
When I try to run this project I have this problem:

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

How can I solve it?

**Comment by Christian-Schiffer** [comment]
I would need a little more information John. I.e. What webserver are you using, are you having the same problem with a fresh asp.net mvc template?

**Comment by Christian-Schiffer** [comment]
Here is what Microsoft says, it is not a problem with the app but with your configuration.

https://support.microsoft.com/nb-no/help/942055/-http-error-500.19-error-when-you-open-an-iis-7.0-webpage
