### ISSUE TITLE
Your username is offensive

### ISSUE THREAD

**Issue by special-snowflak** [Christian-Schiffer/servicelayer.chat#11]
You have word Christian in your username, which means "follower of Christ". As you are not follower of Christ, this is cultural appropriation. Please take an example from Microsoft, which changed their icon to special snowflake and change word Christian in your username to special snowflake. Please make it your top priority.

**Comment by Eirenarch** [comment]
As a Pastafarian I am offended by the word Christian which refers to a religion that has oppressed my religion and pirates for centuries.
