### ISSUE TITLE
Please dont use caps lock for readme

### ISSUE THREAD

**Issue by Polsenols** [Christian-Schiffer/servicelayer.chat#19]
I get startled easily and have anxiety, I just feel like you are shouting at me or commanding me very angrily when your readme file is in all caps. Please rename it to be lower case letters only, thanks.

**Comment by Code-Chapter** [comment]
not only did he abuse his caps lock key, he also used it to write some very naughty words which are very offensive

**Comment by toriningen** [comment]
File should be renamed too. I don't like the fact it's telling me what to do, like "READ ME IMMEDIATELY". I would rather name it "maybe-you-could-read-me-if-you-dont-mind", and kebab case would also emphasize the greatness of Arab culture and benefits of multiculturalism.

Merry Christmas!
