### ISSUE TITLE
Beard on your profile picture and pushing of hair is very offensive to me

### ISSUE THREAD

**Issue by NyxVxyN** [Christian-Schiffer/servicelayer.chat#23]
**The Beard on your display picture and pushing of hair is very offensive to me, additionally chemotherapy has cost people their lives over the centuries and many of the people I know, yet even if that was not the case, pushing hair as part of a display of appearance is completely unacceptable. Please remove the hair immediately and make it your top priority. To me this is almost equally offensive as a nicki minaj.**

_Steps to Reproduce:_

1. Be born during  the baby boom
2. Have existential crisis and choose to write ridiculous requests on Microsoft product updates.

_Does this issue occur when all extensions are disabled?_: Yes, unfortunately disabling extensions does not remove it in the picture, I tried.

_

> For those that actually do get offended in the aforementioned text in regards to the cancer/chemo, I do actually have family members that have died to the treatment process and the illness as well as friends but that does not mean I should crap all over someone else's stuff just because I feel like I should be offended by it, someone has been living in a very sheltered world.

_

**Comment by Christian-Schiffer** [comment]
Thank you for teaching me the true meaning of xmas, as if I did not know it already. You are yet another fine example of why my bug report was necessary.
