### ISSUE TITLE
Please delete more lines

### ISSUE THREAD

**Issue by iquasere** [Christian-Schiffer/servicelayer.chat#29]
![contribution](https://user-images.githubusercontent.com/16226371/71193586-3f38c780-2282-11ea-81f1-f1572307c3b3.png)

I find the number of lines you removed has a purposefully degrading quantification. Please remove more lines. Preferentially, on the issues you raised in other people's repositories 🎅

EDIT: on the title for less offensiveness.

**Comment by toriningen** [comment]
I would say, please do so immediately, and report back to me about measures taken and how you would prevent this from happening in the future.
