### ISSUE TITLE
Offensive language

### ISSUE THREAD

**Issue by spuriklaus** [Christian-Schiffer/servicelayer.chat#3]
I find the F-word offensive, please remove it from your documentation. Thanks.

**Comment by Christian-Schiffer** [comment]
> I find the F-word offensive, please remove it from your documentation. Thanks.

If you find the licence offencive you need to take it up with the licence maker. You can find their pages here: http://www.wtfpl.net/about/

**Comment by Christian-Schiffer** [comment]
User reported. Case closed.
