### ISSUE TITLE
Your site isn't secured, I'm offended

### ISSUE THREAD

**Issue by hotsaucejake** [Christian-Schiffer/servicelayer.chat#31]
Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no

**Comment by Christian-Schiffer** [comment]
> Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no

Thanks for leaving you IP address on my site.

**Comment by Clemens-E** [comment]
Wish you good luck with all the IP addresses, whatever you are planning to do with it (nothing? It's an IP address, not a password)

**Comment by Reynergodoy** [comment]
> > Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no
> 
> Thanks for leaving your IP address on my site.

Is that a threat I am seeing? Now THAT is offensive. Maybe we should report to Microsoft how comprehensive you are, un?

**Comment by OfficalLooper** [comment]
So this snowflake cries to Microsoft over a fucking Santa hat but is trying to threaten people with their I.P?? You do know the rest of the world can play that game and you wont win ;)

**Comment by Christian-Schiffer** [comment]
> > > Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no
> > 
> > 
> > Thanks for leaving your IP address on my site.
> 
> Is that a threat I am seeing? Now THAT is offensive. Maybe we should report to Microsoft how comprehensive you are, un?

 Yes indeed it is, a threat of legal consequences. See trying to hack someones server is a criminal offence, so is uttering death threats, incitement to genocide and such, all offences I have on record. 

You know the song, _bad boy bad boy, watcha gonna go, whatcha gonna do when they come for you?_

**Comment by Reynergodoy** [comment]
> > > > Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no
> > > 
> > > 
> > > Thanks for leaving your IP address on my site.
> > 
> > 
> > Is that a threat I am seeing? Now THAT is offensive. Maybe we should report to Microsoft how comprehensive you are, un?
> 
> Yes indeed it is, a threat of legal consequences. See trying to hack someones server is a criminal offence, so is uttering death threats, incitement to genocide and such, all offences I have on record.
> 
> You know the song, _bad boy bad boy, watcha gonna go, whatcha gonna do when they come for you?_
> Enjoy your freedom, while it lasts.

Very smart of you, twisting my words. I had never even messaged you neither do I think github offers private message function. 

Also, the guy never threatened to hack your servers he might have said your webserver do not posses a Certificate.

So stop twisting other people's words, false accusations are a crime, punishable with months in jail.

You are not qualified to curtail my freedom.

**Comment by aUniqueUser** [comment]
> > > > > Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no
> > > > 
> > > > 
> > > > Thanks for leaving your IP address on my site.
> > > 
> > > 
> > > Is that a threat I am seeing? Now THAT is offensive. Maybe we should report to Microsoft how comprehensive you are, un?
> > 
> > 
> > Yes indeed it is, a threat of legal consequences. See trying to hack someones server is a criminal offence, so is uttering death threats, incitement to genocide and such, all offences I have on record.
> > You know the song, _bad boy bad boy, watcha gonna go, whatcha gonna do when they come for you?_
> > Enjoy your freedom, while it lasts.
> 
> Very smart of you, twisting my words. I had never even messaged you neither do I think github offers private message function.
> 
> Also, the guy never threatened to hack your servers he might have said your webserver do not posses a Certificate.
> 
> So stop twisting other people's words, false accusations are a crime, punishable with months in jail.
> 
> You are not qualified to curtail my freedom.

this thread is a real bruh moment

**Comment by Reynergodoy** [comment]
> > > > > > Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no
> > > > > 
> > > > > 
> > > > > Thanks for leaving your IP address on my site.
> > > > 
> > > > 
> > > > Is that a threat I am seeing? Now THAT is offensive. Maybe we should report to Microsoft how comprehensive you are, un?
> > > 
> > > 
> > > Yes indeed it is, a threat of legal consequences. See trying to hack someones server is a criminal offence, so is uttering death threats, incitement to genocide and such, all offences I have on record.
> > > You know the song, _bad boy bad boy, watcha gonna go, whatcha gonna do when they come for you?_
> > > Enjoy your freedom, while it lasts.
> > 
> > 
> > Very smart of you, twisting my words. I had never even messaged you neither do I think github offers private message function.
> > Also, the guy never threatened to hack your servers he might have said your webserver do not posses a Certificate.
> > So stop twisting other people's words, false accusations are a crime, punishable with months in jail.
> > You are not qualified to curtail my freedom.
> 
> this thread is a real bruh moment

I also think so.

- Threatens someone with their IP

- Points out it is not cool

- Says, 'I will sue you because you threatened my life'

Not very logical
