### ISSUE TITLE
Owner of this repository is a special snowflake

### ISSUE THREAD

**Issue by Enerccio** [Christian-Schiffer/servicelayer.chat#312]

**Comment by kittenswolf** [comment]
I get that you don't like the owner of the repo, but this is a bit too much imo. Leave the dude alone. Almost seems like you're more triggered than he was 😉

**Comment by CatTheHacker** [comment]
@kittenswolf I fail to see how someone can be more triggered than the person opening an issue on Santa hat comparing it to killing jews.

**Comment by Mixterio** [comment]
@kittenswolf as a matter of fact I am. This much stupidity gave me a dizziness attack. I will have to contact my psychiatrist because of this.

**Comment by Christian-Schiffer** [comment]
> @kittenswolf I fail to see how someone can be more triggered than the person opening an issue on Santa hat comparing it to killing jews.

Had you actually read the reasoning I provided when opening the issue you would know that the xmas and the santa hat indeed have been used exceedingly throughout history to instigate genocidal murder, torture and horrancement of the Jewish people. 

Moreover, that very xmas spirit has proven to be very alive and kicking given the death threats, hitler saluting santas,  jew hatred and hatred of people of color and more you guys presented me with here and in my personal email box in the aftermath of me opening the issue. Proving the necessity to keep such religious hate symbols away from professional software that should have no religious content whatsoever. 

So, thank you for yet another prime example of the true xmas spirit.
