### ISSUE TITLE
🎅

### ISSUE THREAD

**Issue by haertner** [Christian-Schiffer/servicelayer.chat#315]
🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by haertner** [comment]
Cry me a river bastard.

**Comment by lookaflyingfish** [comment]
🎅

**Comment by Christian-Schiffer** [comment]
Thank you for yet another prime example of the true xmas spirit.
