### ISSUE TITLE
🎅 Santa will soon be in your house!

### ISSUE THREAD

**Issue by AlexGalays** [Christian-Schiffer/servicelayer.chat#316]
![image](https://user-images.githubusercontent.com/1375586/71299100-d178c280-238b-11ea-8d36-967c6ab10600.png)

**Comment by lookaflyingfish** [comment]
YOU BETTER WATCH OUT
YOU BETTER NOT CRY
BETTER NOT POUT
I'M TELLING YOU WHY
SANTA CLAUS IS COMING TO TOWN

HE'S MAKING A LIST
AND CHECKING IT TWICE;
GONNA FIND OUT WHO'S NAUGHTY AND NICE
SANTA CLAUS IS COMING TO TOWN

HE SEES YOU WHEN YOU'RE SLEEPING
HE KNOWS WHEN YOU'RE AWAKE
HE KNOWS IF YOU'VE BEEN BAD OR GOOD
SO BE GOOD FOR GOODNESS SAKE!
O! YOU BETTER WATCH OUT!
YOU BETTER NOT CRY
BETTER NOT POUT
I'M TELLING YOU WHY
SANTA CLAUS IS COMING
SANTA CLAUS IS COMING
SANTA CLAUS IS COMING TO TOWN

**Comment by Christian-Schiffer** [comment]
Thank you for yet another prime example of the xmas spirit.
