### ISSUE TITLE
Fyi

### ISSUE THREAD

**Issue by CatTheHacker** [Christian-Schiffer/servicelayer.chat#322]
https://github.com/Christian-Schiffer/servicelayer.chat/issues/312#issuecomment-568177078
This would have never been brough up without your issue on santa hat, so feel responsible for that.

**Comment by Christian-Schiffer** [comment]
As I said, had you actually read the reasoning I provided when opening the issue you would know that the xmas and the santa hat indeed have been used exceedingly throughout history to instigate genocidal murder, torture and horrancement of the Jewish people.

Moreover, that very xmas spirit has proven to be very alive and kicking given the death threats, hitler saluting santas, jew hatred and hatred of people of color and more you guys presented me with here and in my personal email box in the aftermath of me opening the issue. Proving the necessity to keep religious and hate symbols away from professional software that should have no religious content whatsoever.

Now you blaming me for your own murderous and genocidal rage against me, Jews, people of color as well as other groups does in no way improve my image of you.

So, thank you for yet another prime example of the true xmas spirit.

**Comment by KaMiila** [comment]
#firstworldproblem its nice to see that things are going so well for you, you have to invent problems.  I think you need to learn about correlation.  A Santa hat on a gear icon has no correlation to the Jewish/Christian issues.  You were seeking attention, you received the attention, own up to it.

**Comment by wigums** [comment]
tl;dr
