### ISSUE TITLE
> Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no

### ISSUE THREAD

**Issue by Reynergodoy** [Christian-Schiffer/servicelayer.chat#38]
> Please let me know when this is a safe space and I can visit again: https://www.servicelayer.no

Thanks for leaving your IP address on my site.

_Originally posted by @Christian-Schiffer in https://github.com/Christian-Schiffer/servicelayer.chat/issues/31#issuecomment-567622094_

Christian Schiffer is being offensive. Please leave this community, you are offensive.

**Comment by atlassanjay** [comment]
Santa does not approve of SSL

**Comment by OfficalLooper** [comment]
At this point i think he is just trolling and pissing people off.

**Comment by Reynergodoy** [comment]
> At this point i think he is just trolling and pissing people off.

I agree
