### ISSUE TITLE
You must be fun at parties

### ISSUE THREAD

**Issue by gonmf** [Christian-Schiffer/servicelayer.chat#43]
```
         |
        -+-
         A
        /=\               /\  /\    ___  _ __  _ __ __    __
      i/ O \i            /  \/  \  / _ \| '__|| '__|\ \  / /
      /=====\           / /\  /\ \|  __/| |   | |    \ \/ /
      /  i  \           \ \ \/ / / \___/|_|   |_|     \  /
    i/ O * O \i                                       / /
    /=========\        __  __                        /_/    _
    /  *   *  \        \ \/ /        /\  /\    __ _  ____  | |
  i/ O   i   O \i       \  /   __   /  \/  \  / _` |/ ___\ |_|
  /=============\       /  \  |__| / /\  /\ \| (_| |\___ \  _
  /  O   i   O  \      /_/\_\      \ \ \/ / / \__,_|\____/ |_|
i/ *   O   O   * \i
/=================\
       |___|

```

**Comment by OfficalLooper** [comment]
🎅Merry Christmas everyone!!!🎅

**Comment by AmyrAhmady** [comment]
Your name is pushing a religion and it's offensive to me as a Muslim and many other fellow muslim brothers.
I'd be glad if you change your name as soon as possible Mr. Christian; It's hurting my feelings and I can't stay on the internet when I know there's someone called Christian, but I'm a developer and I need to work. It's just making it very hard for me.
It is also a reminder of jesus and how badly he died in pain, so your name is also offensive to christian people

Please, change your name, I have an evidence of you having that name and I will attach it to this post

![image](https://user-images.githubusercontent.com/34688664/71210863-2a305880-22c3-11ea-8214-cf7d76c3f8ff.png)
