### ISSUE TITLE
Offensive License Wording

### ISSUE THREAD

**Issue by MLDMoritz** [Christian-Schiffer/servicelayer.chat#45]
Hey,

I really feel uncomfortable reading these parts in your license:

`DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE`

I am literally shaking right now about your language.

**Comment by sprintr** [comment]
I am offended by the existence of this repo.

**Comment by MLDMoritz** [comment]
This will be closed pretty soon, however - closing this issue just proves the case that the repository owner is not interested in an inclusive world where everyone can share their concerns.

**Comment by sprintr** [comment]
Merry Christmas @MLDMoritz

**Comment by sprintr** [comment]
🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅

**Comment by KeepBotting** [comment]
merry christmas

**Comment by maarten-wachters** [comment]
Look man, I also think the VSC thing is a bit ridiculous but griefing his repository's by raising false issues is _way_ above the conduct here expected of you on github.

**Comment by KeepBotting** [comment]
@maarten-wachters that'd be *below*, i expect, not *above*

i think the assumption that these issues are false is offensive, and request that you delete your comment

**Comment by sprintr** [comment]
@maarten-wachters I find your name offensive, please remove your account ASAP.

**Comment by maarten-wachters** [comment]
I refer you both to : https://help.github.com/en/github/site-policy/github-community-guidelines

**Comment by mikegibney** [comment]
The people claiming that Christian is being an easily offended snowflake are going to respond to it by cyberbullying him _like reasonable, well adjusted adults_. Cool cool cool, our industry and culture is broken.

**Comment by arrterian** [comment]
@MLDMoritz @sprintr Merry Christmas guys 🎅

**Comment by ddugovic** [comment]
There is actually a problem with the license:

> Everyone is permitted to copy and distribute verbatim or modified copies of this license document, and changing it is allowed as long as the name is changed.

This project's readme doesn't include a verbatim copy of the license but contains additional words.

**Comment by nallg00d** [comment]
I am offended as this phrasing and it violates community policies please shut it down

**Comment by nickeuk** [comment]
> Hey,
> 
> I really feel uncomfortable reading these parts in your license:
> 
> `DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE`
> 
> I am literally shaking right now about your language.

it's a real thing https://en.wikipedia.org/wiki/WTFPL

**Comment by notviri** [comment]
ok, now this is epic

**Comment by nallg00d** [comment]
I am also pretty offended by this. I would suggest "Do what the heck you want to public license" or use something like BSD/MIT which essentially say the same thing.

**Comment by MLDMoritz** [comment]
@nickeuk Even if its real, i could easily be offended by this.

**Comment by SnowboiTheGr8** [comment]
The name Christian offends me because it reminds me of santa hats

**Comment by Jan200101** [comment]
@SnowboiTheGr8 thats just rude

**Comment by Yomanz** [comment]
> 
> 
> The name Christian offends me because it reminds me of santa hats

I am uncomfortable with the use of "Snow" in your name as it reminds me of santa.
This is not politically correct and I would hope that you should be able to identify and fix the issues asap before I contact github abuse.

**Comment by Jan200101** [comment]
This is rather embarrassing to see this community berate someone for something like this
Is it so hard to talk with reason and not be an asshole about it?

**Comment by Enerccio** [comment]
How is Santa even related to Christianity?

**Comment by Enerccio** [comment]
> This is rather embarrassing to see this community berate someone for something like this
> Is it so hard to talk with reason and not be an asshole about it?

Well you reap what you sow... he was asshole now people will be asshole to him

**Comment by Jan200101** [comment]
how was he an asshole? he brought up his issues and the VSCode team agreed to remove it
He didn't go around screaming bloody murder getting a mob to enforce it

**Comment by Enerccio** [comment]
> how was he an asshole? he brought up his issues and the VSCode team agreed to remove it
> He didn't go around screaming bloody murder getting a mob to enforce it

Issue of a freaking santa hat. He overreacted like a special snowflake and now he eats his desserts. People don't like when special snowlake is "offended" by something that is literally not offending to anyone normal and they are even more pissed when other people (like M$ VSCode team) pander to people like that.

**Comment by Jan200101** [comment]
I do not agree with Christian but its his opinion and labeling anything that goes against your opinion as a snowflake is incredibly toxic
Christian had been mature over almost the entire thing (with some exception in this repo which I'll look over because its targeted harrasment) meanwhile all I've seen most of you do is yell and scream
now there are countless issues on the VSCode repo because people like you decided they could stick it to the VSCode team

there are people out there that have responded to this better than most of you for example
[#87476](https://github.com/microsoft/vscode/issues/87476) or [#87468](https://github.com/microsoft/vscode/issues/87468)

**Comment by maarten-wachters** [comment]
> > how was he an asshole? he brought up his issues and the VSCode team agreed to remove it
> > He didn't go around screaming bloody murder getting a mob to enforce it
> 
> Issue of a freaking santa hat. He overreacted like a special snowflake and now he eats his desserts. People don't like when special snowlake is "offended" by something that is literally not offending to anyone normal and they are even more pissed when other people (like M$ VSCode team) pander to people like that.

So you take offense to him taking offense, yet fail to see the hypocrisy of your ways.

**Comment by julijane** [comment]
In my opinion somehow comparing a Santa Hat with the killing of many people is quite bad and a trivialization of murder. In my opinion the original bug report was therefore in quite bad taste and drawing this connection makes the bug reporter an awful person (which other here have more bluntly phrased as him being an "asshole"). If you are really concerned about the issue at hand here (murdering of jews in the past) you should refrain from making the topic a laughing matter.

Either the bug reporter was trolling then he is a awful person. Or he really meant it, then he is "only" very ignorant for the aforementioned reasons.

**Comment by Jan200101** [comment]
sure but none of that allows anyone to go ahead and open issues on his projects with the goal of harrassing him regarding that

**Comment by Tigatok** [comment]
> @nickeuk Even if its real ... while Santa is not real.

What do you mean

**Comment by julijane** [comment]
> sure but none of that allows anyone to go ahead and open issues on his projects with the goal of harrassing him regarding that

Well that is your interpretation of what is going on here. I find it quite lame of you to dismiss the issue like that. What is actually happening here is that people point out that there are many things other people might get offended about. The name of the license is offensive language for sure and people just point out that it is self-righteous to be offended by some issue but then show own behavior which offends others.

What gives him or you the right to decide which complaint about offensive issues is justified and which one is not?

**Comment by Jan200101** [comment]
I see that this sets a bad precedent in regards to what can be changed just because someone is "offended" about it but everyone jumping on that person or opening various issues in attempts to get rid of other "offending" things does not help anyone

**Comment by julijane** [comment]
It also does not help to jump to conclusions and just claim that the bug report here is only meant as "harassment" or "retaliation" which totally ignoring that the issue reporter actually has a valid point. This is what I said, somehow you feel you have a right to decide which issue is "serious" / "honest" and which one is not. You should really think about what you are doing here and how you are not better than the people you are criticizing if you just dismiss the bug report because you have just decided that it is not to be taken serious. Pot calling the kettle black, really.

**Comment by RubyTheRose** [comment]
We've all come to this random github repo.

**Comment by Bubblebug17** [comment]
I am offended by the existence of this issue.

**Comment by mitsukuri** [comment]
The license should read:
`DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE, EXCEPT PUTTING A SANTA HAT ON IT`
Now that's the politically correct way to do whatever the fuck one wants!

**Comment by Rotbot9k** [comment]
Fuck this guy am I right?

**Comment by KaySackey** [comment]
Ignoring the Santa hat controversy, I am legitimately bothered by sexual language in a legal license. It would be better to just use the MIT or BSD with a patent rider.

The poor language choice leads to this repo being censored on some corporate and country level networks, and means that I have to use sexual terminology if ever I need to defend my inclusion of this repo in an existing codebase.

It’s not necessary for anything except “fun” and that isn’t a good reason for anyone in a professional setting, least of all a moralist person like the author seems to be. 

Again, please do not close this issue merely because of spite due to backlash you a receiving, and consider changing the license for the betterment of us all.

Language choice matters.

**Comment by AdolfTheHitler** [comment]
Can someone Please fork this repo and add a Christmas theme? Then do a PR

**Comment by lookaflyingfish** [comment]
🎅

**Comment by nzalog** [comment]
Wonder when companies will learn... Literally anything can be found offensive if you find the right person. It near impossible to create something that won't offend someone somewhere in any way.

**Comment by Master-Foo** [comment]
@maarten-wachters The existence of the `DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE` pretty much gives everyone permission to make issues @Christian-Schiffer about the license. He gave everyone permission to `DO WHAT THE FUCK YOU WANT`

**Comment by Christian-Schiffer** [comment]
Thank you for yet another prime example of the true xmas spirit.

**Comment by Christian-Schiffer** [comment]
As to the licence, if you don't like it, don't download it, also requests for changes on it needs to be directed towards the copyright holder of said licence, you'll find contact info as part of the licence.
