### ISSUE TITLE
Filter santa emoji

### ISSUE THREAD

**Issue by linvain** [Christian-Schiffer/servicelayer.chat#46]
Every chat should filter messages with santa emoji (🎅) because it is too offensive!!

I'm literally crying right now...

**Comment by KaMiila** [comment]
You need to change your name, it is offensive to me.  Do you know what the Christians have done to humanity?  Seriously, stop being so offensive!

**Comment by wasddd-bit** [comment]
🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by Christian-Schiffer** [comment]
Thank you for yet another prime example of the true xmas spirit.
