### ISSUE TITLE
i am offended

### ISSUE THREAD

**Issue by BaHeK1994** [Christian-Schiffer/servicelayer.chat#48]
remove the Jews, they killed Jesus and insult my feelings of the believer

**Comment by wasddd-bit** [comment]
I am also offended. And this is all that matters. I want an apology and the removal of you account because      YOU    ARE         OFFENSIVE TOOOO ME ME ME ME  !!!!!!!!!!!!!!!!!!!!!!!!!!! 
🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by Christian-Schiffer** [comment]
Thank you for yet another prime example of the true xmas spirit.
